project:
  type: website
  output-dir: docs


website:
  title: "TECH3 Applied statistics"
  image: images/nhh.png
  page-navigation: true
  navbar:
    background: primary
    logo: images/nhh.png
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Calender"
        href: calender.qmd
      - text: "Modules"
        href: module-1.qmd
      - text: "Datalabs"
        href: datalab-1.qmd
      - text: "Python basics"
        href: pythonbasics.qmd
      - text: "Old exams"
        href: oldexams.qmd
      - text: "Reference"
        href: reference.qmd

  sidebar:
    - title: "Datalabs"
      style: "docked"
      collapse-level: 1
      search: true
      background: light
      contents:
        - datalab-1.qmd
        - datalab-2.qmd
        
    - title: "Modules"
      contents: 
         - section: "Module 1: Summarizing and visualizing data"
           contents:
             - href: module-1.qmd
               text: "Textbook"
             - 01-videos.qmd
             - 01-exercises.qmd
             - 01-python.qmd
         - section: "Module 2: Probability, random variables, probability distributions and simulations."
           contents: 
             - href: module-2.qmd
               text: "Textbook"
             - href: 2_exercises.qmd
               text: "Exercises"
         - section: "Module 3: Estimation, sampling distributions and resampling"
           contents: 
             - href: module-3.qmd
               text: "Textbook"
         - section: "Module 4: Designing studies, hypothesis testing, and quantifying effects"
           contents: 
             - href: module-4.qmd
               text: "Textbook"
         - section: "Module 5: Measuring relationships and fitting models"
           contents: 
             - href: module-5.qmd
               text: "Textbook"
             
    - title: "Python basics"
      contents:
        - pythonbasics.qmd
        # navigation items

    - title: "Old exams"
      contents:
        - oldexams.qmd
        # navigation items

    - title: "Reference"
      contents:
        - reference.qmd
        # navigation items

editor: visual


          
format:
  html:
    theme: 
        - cosmo
        - custom.scss
    css: style.css
    toc: true
    # toc-depth: 1
    # fontsize: 1.1em
    # linestretch: 1.7
    # number-sections: true
    # number-debth: 2
    # html-math-method: katex
